# Default values for broker app
# This is a YAML-formatted file.

global:
  name: "nr-broker-app"
  environment: "development"
<<<<<<< Updated upstream
=======
  envtag: "dev"
  envlable: "nonprod"
>>>>>>> Stashed changes
  vault: "https://vault-iit.apps.silver.devops.gov.bc.ca"

server:
  image:
    registry: "artifacts.developer.gov.bc.ca"
    context: "/ba03-docker-local"

  resources:
    replicas: 1
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 256Mi

  route:
    internal:
      enabled: true
      host: chart-example.local
    vanity:
      enabled: false
      host: chart-example.local