# Default values for vault sync.
# This is a YAML-formatted file.

global:
  name: "nr-broker-app"
  environment: "development"
  vault: "https://vault-iit.apps.silver.devops.gov.bc.ca"

server:
  image:
    repository: "image-registry.openshift-image-registry.svc:5000"
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 256Mi

  route:
    internal:
      enabled: true
      host: chart-example.local
    vanity:
      enabled: false
      host: chart-example.local