apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nr-broker
  labels:
    helm.sh/chart: {{ .Values.global.name }}
    app: {{ .Values.global.name }}
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: "{{ .Values.server.image.registry }}{{ .Values.server.image.context }}/bcgov-nr/nr-broker-backend:v{{ .Values.global.version }}"
      referencePolicy:
        type: Local