apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nr-broker
  labels:
    helm.sh/chart: {{ .Values.global.name }}
    app: {{ .Values.global.name }}
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations: null
      from:
        kind: ImageStreamTag
        namespace: {{ regexReplaceAll "-[a-zA-Z0-9]+" .Release.Namespace "-tools" }}
        name: nr-broker:{{ .Values.global.envtag }}
      referencePolicy:
        type: Local