{{- $licensePlate := regexFind "^[a-zA-Z0-9]+" .Release.Namespace -}}
{{- $envTag := regexFind "[a-zA-Z0-9]+$" .Release.Namespace -}}
{{- $envLabel := eq $envTag "prod" | ternary "prod" "nonprod" -}}
{{- $envTokenPath := printf "%s-%s/%s-token" $licensePlate $envLabel $envTag -}}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: {{ .Values.global.name }}
    helm.sh/chart: {{ .Values.global.name }}
  name: {{ .Values.global.name }}
spec:
  replicas: {{ .Values.server.resources.replicas }}
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - nr-broker
        from:
          kind: ImageStreamTag
          namespace: {{ .Release.Namespace }}
          name: nr-broker:latest
  selector:
    deploymentconfig: {{ .Values.global.name }}
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: {{ .Values.global.name }}
        deploymentconfig: {{ .Values.global.name }}
    annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-config: {{ $envTokenPath }}
        vault.hashicorp.com/agent-inject-template-config: |
          {{`{{- with secret `}}"{{ $envTokenPath }}" {{` }}
          export BROKER_TOKEN="{{ .Data.data.BROKER_TOKEN }}"
          export VAULT_TOKEN="{{ .Data.data.VAULT_TOKEN }}"
          {{ end `}} }}
        vault.hashicorp.com/auth-path: auth/k8s-CLUSTER
        vault.hashicorp.com/namespace: {{ .Release.Namespace }}
        vault.hashicorp.com/role: {{ $envLabel }}
    spec:
      serviceAccountName: {{ $licensePlate }}-vault
      containers:
        - image: nr-broker:latest
          imagePullPolicy: Always
          name: nr-broker
          args: ['sh', '-c', 'source /vault/secrets/config && envconsul -config env.hcl node dist/main']
          env:
            - name: APP_ENVIRONMENT
              value: {{ .Values.global.environment }}
            - name: VAULT_ADDR
              value: {{ .Values.global.vault }}
            - name: HTTP_BASIC_USER
              valueFrom:
                secretKeyRef:
                  name: nr-broker-basic-creds
                  key: user
            - name: HTTP_BASIC_PASS
              valueFrom:
                secretKeyRef:
                  name: nr-broker-basic-creds
                  key: password
            - name: NO_COLOR
              value: "true"
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.server.resources.limits.cpu | quote }}
              memory: {{ .Values.server.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.server.resources.requests.cpu | quote }}
              memory: {{ .Values.server.resources.requests.memory | quote }}
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5