{{- $licensePlate := regexFind "^[a-zA-Z0-9]+" .Release.Namespace -}}
{{- $envTag := regexFind "[a-zA-Z0-9]+$" .Release.Namespace -}}
{{- $envLabel := eq $envTag "prod" | ternary "prod" "nonprod" -}}
{{- $envTokenPath := printf "%s-%s/%s-token" $licensePlate $envLabel $envTag -}}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: {{ .Values.global.name }}
    helm.sh/chart: {{ .Values.global.name }}{{- if .Values.vault.agent.enabled }}
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/agent-inject-secret-config: {{ $envTokenPath }}
    vault.hashicorp.com/agent-inject-template-config: |
      {{`{{- with secret `}}"{{ $envTokenPath }}" {{` }}
      export BROKER_TOKEN="{{ .Data.data.BROKER_TOKEN }}"
      export VAULT_TOKEN="{{ .Data.data.VAULT_TOKEN }}"
      {{ end `}} }}
    vault.hashicorp.com/auth-path: auth/k8s-silver
    vault.hashicorp.com/namespace: platform-services
    vault.hashicorp.com/role: {{ $licensePlate }}-{{ $envLabel }}
    vault.hashicorp.com/agent-limits-cpu: {{ .Values.vault.agent.limits.cpu }}
    vault.hashicorp.com/agent-requests-cpu: {{ .Values.vault.agent.requests.cpu }}
    vault.hashicorp.com/agent-limits-mem: {{ .Values.vault.agent.limits.memory }}
    vault.hashicorp.com/agent-requests-mem: {{ .Values.vault.agent.requests.memory }}{{- end }}
  name: {{ .Values.global.name }}
spec:{{- if .Values.vault.agent.enabled }}
  serviceAccountName: {{ $licensePlate }}-vault{{- end }}
  replicas: {{ .Values.server.resources.replicas }}
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - nr-broker{{- if .Values.vault.agent.enabled }}
        command: ["/bin/bash"]
        args: ['-c', 'source /vault/secrets/config && envconsul -config env.hcl node dist/main']{{- end }}
        from:
          kind: ImageStreamTag
          namespace: {{ .Release.Namespace }}
          name: nr-broker:latest
  selector:
    deploymentconfig: {{ .Values.global.name }}
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: {{ .Values.global.name }}
        deploymentconfig: {{ .Values.global.name }}
        redis-client: 'true'
    spec:
      containers:
        - image: nr-broker:latest
          imagePullPolicy: Always
          name: nr-broker
          env:
            - name: APP_ENVIRONMENT
              value: {{ .Values.global.environment }}
            - name: VAULT_ADDR
              value: {{ .Values.global.vault }}{{- if .Values.vault.agent.enabled }}{{- else }}
            - name: BROKER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: broker-token
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vault-token{{- end }}
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: HTTP_BASIC_USER
              valueFrom:
                secretKeyRef:
                  name: nr-broker-basic-creds
                  key: user
            - name: HTTP_BASIC_PASS
              valueFrom:
                secretKeyRef:
                  name: nr-broker-basic-creds
                  key: password
            - name: USER_ADMIN
              valueFrom:
                secretKeyRef:
                  name: nr-broker-user-roles
                  key: admin
            - name: USER_DBA
              valueFrom:
                secretKeyRef:
                  name: nr-broker-user-roles
                  key: dba
            - name: USER_DEVELOPER
              valueFrom:
                secretKeyRef:
                  name: nr-broker-user-roles
                  key: developer
            - name: NO_COLOR
              value: "true"
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.server.resources.limits.cpu | quote }}
              memory: {{ .Values.server.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.server.resources.requests.cpu | quote }}
              memory: {{ .Values.server.resources.requests.memory | quote }}
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 5