apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: {{ .Values.global.name }}
    helm.sh/chart: {{ .Values.global.name }}
  name: {{ .Values.global.name }}
spec:
  replicas: 1
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - nr-broker
        from:
          kind: ImageStreamTag
          namespace: {{ .Release.Namespace }}
          name: 'nr-broker:latest'
  selector:
    deploymentconfig: {{ .Values.global.name }}
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: {{ .Values.global.name }}
        deploymentconfig: {{ .Values.global.name }}
    spec:
      containers:
        - image: nr-broker
          imagePullPolicy: Always
          name: nr-broker
          env:
            - name: VAULT_ADDR
              value: {{ .Values.global.vault }}
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: broker-token
            - name: HTTP_BASIC_USER
              valueFrom:
                secretKeyRef:
                  name: nr-broker-basic-creds
                  key: user
            - name: HTTP_BASIC_PASS
              valueFrom:
                secretKeyRef:
                  name: nr-broker-basic-creds
                  key: password
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.server.resources.limits.cpu | quote }}
              memory: {{ .Values.server.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.server.resources.requests.cpu | quote }}
              memory: {{ .Values.server.resources.requests.memory | quote }}
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5