kind: Secret
apiVersion: v1
metadata:
  name: nr-broker-jwt-creds
  labels:
    app: "nr-broker-app"
    helm.sh/chart: "nr-broker-app"
    name: "nr-broker-app"
stringData:
  secret: {{ .Values.auth.jwt_secret }}