kind: Secret
apiVersion: v1
metadata:
  name: vault
  labels:
    app: "nr-broker-app"
    helm.sh/chart: "nr-broker-app"
    name: "nr-broker-app"
stringData:
  broker-token: {{ .Values.vault.brokertoken }}
  vault-token: {{ .Values.vault.fluentbittoken }}