kind: Secret
apiVersion: v1
metadata:
  name: nr-broker-basic-creds
  labels:
    app: "nr-broker-app"
    helm.sh/chart: "nr-broker-app"
    name: "nr-broker-app"
stringData:
  user: {{ .Values.auth.user }}
  password: {{ .Values.auth.password }}