apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nr-broker-build
  labels:
    helm.sh/chart: {{ .Values.global.name }}
    app: {{ .Values.global.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.build.storage.workspace }}
