name: Sample Runner

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      name:
        description: 'Environment to run against'
        type: string
        required: true

jobs:

  run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Get Vault Access
        run: sh ./.github/workflows/vault-token-script.sh
        env:
          BROKER_ADDR: ${{ vars.BROKER_ADDR }}
          BROKER_JWT: ${{ secrets.BROKER_JWT }}
          VAULT_ADDR: ${{ vars.VAULT_ADDR }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_ENVIRONMENT: ${{ inputs.name }}
      - run: echo "hi!"
        env:
          VAULT_ADDR: ${{ vars.VAULT_ADDR }}
      - name: Cleanup Vault Access
        run: sh ./.github/workflows/token-cleanup.sh
        env:
          BROKER_ADDR: ${{ vars.BROKER_ADDR }}
          VAULT_ADDR: ${{ vars.VAULT_ADDR }}