name: Main Merge

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".**"
      - "**.md"
      - "**.yml"
      - "**.yaml"

env:
  REGISTRY: ghcr.io
  NAME: gfp

jobs:
  cancel-prev-runs:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  view-context:
    # https://docs.github.com/en/actions/learn-github-actions/contexts
    name: View GitHub Context
    runs-on: ubuntu-latest
    steps:
      - name: Echo GitHub context
        uses: satackey/action-js-inline@v0.0.2
        with:
          script: |
            const github = require('@actions/github');
            console.log(JSON.stringify(github, null, 2));

  codeql:
    name: Semantic Code Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below)
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  cleanup-ghcr:
    name: Cleanup Container Registry
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/ghcr-io-container-cleanup
      - name: Delete old packages
        uses: davahome/ghcr-cleanup@v1.1.0.1
        with:
          delete_untagged: 1
          keep_versions: 10
          keep_versions_untagged: 0
          minimum_days: 14
          owner: orgs/bcgov-nr
          package: ${{ github.event.repository.name }}
          skip_tags: prod-backend
          token: ${{ secrets.GITHUB_TOKEN }}
